name: Push Executable to Public Repo

on:
  push:
    paths:
      - 'startScript.sh'
  workflow_dispatch:
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Encrypt file
      run: |
        sudo apt-get install -y build-essential shc
        shc -f startScript.sh -o script   
    - name: Push Executable to Repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'script'
        destination_repo: 'lupree/m159'
        destination_branch: 'master'
        user_email: 'luca.ramseyer@lupree.com'
        user_name: 'lupree'
        commit_message: 'Updated Executable File'
